export const images: Record<string, any> = {
  abara: require('./ABARÁ.png'),
  acaraje: require('./ACARAJÉ.png'),
  acaca: require('./ACAÇÁ.png'),
  balaDeVidro: require('./BALA-DE-VIDRO.png'),
  boboDeCamarao: require('./BOBÓ-DE-CAMARÃO.png'),
  caruru: require('./CARURU.png'),
  cocada: require('./COCADA.png'),
  cozido: require('./COZIDO.png'),
  cuscuze: require('./CUSCUZ.png'),
  dobradinha: require('./DOBRADINHA.png'),
  efo: require('./EFÓ.png'),
  feijaoDeAzeite: require('./FEIJÃO DE AZEITE.png'),
  feijaoDeLeite: require('./FEIJÃO-DE-LEITE.png'),
  feijoada: require('./feijoada.png'),
  frigideira: require('./FRIGIDEIRA.png'),
  fumeiro: require('./FUMEIRO.png'),
  galinhaMolhoPardo: require('./GALINHA-MOLHO-PARDO.png'),
  malassado: require('./MALASSADO.png'),
  manicoba: require('./MANIÇOBA.png'),
  mininicoDeCarneiro: require('./MININICO-DE-CARNEIRO.png'),
  mocoto: require('./MOCOTÓ.png'),
  moqueca: require('./MOQUECA.png'),
  mugunza: require('./MUGUNZÁ.png'),
  passarinha: require('./passarinha.png'),
  punheta: require('./PUNHETA.png'),
  quiabada: require('./QUIABADA.png'),
  rabada: require('./RABADA.png'),
  sarapatel: require('./SARAPATEL.png'),
  vatapa: require('./VATAPÁ.png'),
  xinxinDeBofe: require('./XINXIM-DE-BOFE.png'),
  xinxinDeGalinha: require('./XINXIM-DE-GALINHA.png'),
};