export const images: Record<string, any> = {
  aipim: require('./AIPIM.png'),
  alho: require('./ALHO.png'),
  amendoinECastanho: require('./AMENDOIM-E-CASTANHA.png'),
  azeiteDeDende: require('./AZEITE-DE-DENDÊ.png'),
  azeiteDende: require('./AZEITE-DENDÊ.png'),
  acucar: require('./AÇÚCAR.png'),
  batata: require('./BATATA.png'),
  boboComIngrediente: require('./BOBO-COM-INGREDIENTE.png'),
  bofe: require('./BOFE.png'),
  bucho: require('./BUCHO.png'),
  calabresaECarneQuiabada: require('./CALABRESA-E-CARNE-QUIABADA.png'),
  calabresa: require('./CALABRESA.png'),
  camarao: require('./CAMARAO.png'),
  camaraoFresco: require('./CAMARÃO-FRESCO.png'),
  camaraoSeco: require('./CAMARÃO-SECO.png'),
  canela: require('./CANELA.png'),
  carneDeFumeiro: require('./CARNE-DE-FUMEIRO.png'),
  carne: require('./CARNE.png'),
  cebola: require('./CEBOLA.png'),
  cebolinha: require('./CEBOLINHA.png'),
  charque2: require('./CHARQUE (2).png'),
  charque: require('./CHARQUE.png'),
  coco: require('./COCO.png'),
  coentro: require('./COENTRO.png'),
  dende: require('./DENDE.png'),
  feijaoBranco: require('./FEIJÃO BRANCO.png'),
  feijao: require('./FEIJÃO.png'),
  folhaDeLouro: require('./FOLHA DE LOURO.png'),
  folhaDeBananeira: require('./FOLHA-DE-BANANEIRA.png'),
  fradinho: require('./FRADINHO.png'),
  frango: require('./FRANGO.png'),
  fuba: require('./FUBÁ.png'),
  leiteCoco: require('./LEITE-COCO.png'),
  leiteCondensado: require('./LEITE-CONDENSADO.png'),
  leiteDeCoco: require('./LEITE-DE-COCO.png'),
  linguaDeVaca: require('./LINGUA-DE-VACA.png'),
  linguica: require('./LINGUICA.png'),
  mandioca: require('./MANDIOCA.png'),
  manteiga: require('./MANTEIGA.png'),
  milhoBranco: require('./MILHO-BRANCO.png'),
  mionMalassado: require('./MION MALASSADO.png'),
  ovo: require('./OVO.png'),
  passarinhaIngrediente: require('./PASSARINHA-INGREDIENTE.png'),
  pimentaDeCheiro: require('./PIMENTA-DE-CHEIRO.png'),
  pimentao: require('./PIMENTÃO.png'),
  postaDePeixe: require('./POSTA-DE-PEIXE.png'),
  pao: require('./PÃO.png'),
  quiabo: require('./QUIABO.png'),
  rabo: require('./RABO.png'),
  sal: require('./SAL.png'),
  tomate: require('./TOMATE.png'),
  verduras: require('./VERDURAS.png'),
};